baseURL = "https://blog.psammiteslab.fr"
title = "Psammites Lab"
defaultContentLanguage = "fr"

[params]
  author = "Clément Di Domenico"

[[params.socials]]
  name = "GitHub"
  url = "https://github.com/Clemsazert"

[[params.socials]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/clément-di-domenico-79a33614a"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    [languages.fr.params]
      description = "WIP mon blog"
  [languages.en]
    languageName = "English"
    weight = 2
    [languages.en.params]
      description = "WIP my blog"
